nav:
  - index.md
  - 시동 절차.md
  - 이륙 및 이함.md
  - 웨이포인트.md
  - 착륙.md
  - 기총(공대지).md
  - 로켓.md
  - 무유도(Unguide) 폭탄.md
  - 타겟팅포드 ATFLIR.md
  - ADM-141 탈드(TALD).md
  - AGM-62 Walleye II.md
  - 레이저유도폭탄.md
  - JDAM & JSOW.md
  - AGM-84D Harpoon.md
  - AGM-84 SLAM(ER).md
  - AGM-65 Maverick.md
  - AGM-88C HARM.md
  - 무장데이터링크포드.md
  - 기총(공대공).md
  - AIM-7 Sparrow.md
  - AIM-9 Sidewinder.md
  - AIM-120 Amrram.md
  - 착함.md
  - 기타.md
  - "*"
