on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure Git Credentials
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: requirements.txt

      - name: Cache MkDocs build artifacts
        uses: actions/cache@v4
        with:
          path: .cache
          key: mkdocs-${{ runner.os }}-${{ hashFiles('mkdocs.yml') }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            mkdocs-${{ runner.os }}-

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Deploy
        run: |
          mkdocs gh-deploy --force

